##### To be able to use numpy's libraries - as always in any other language - it needs an import.
##### "np" is the usual and most widely used alias for numpy.

In [2]:
import numpy as np

###### Regular array examples in Python

In [3]:
regular_array = [1, 2, 3, 4]
regular_array

[1, 2, 3, 4]

###### The type of this array is

In [4]:
type(regular_array)

list

###### To get a numpy array from Python array use array function of np

In [5]:
np_array = np.array(regular_array)

In [6]:
np_array

array([1, 2, 3, 4])

###### Notice the type of above array is not list, but it is numpy.ndarray

In [7]:
type(np_array)

numpy.ndarray

The numpy arrays can be accesses just like regular arrays + its own way.

In [8]:
np_array[2]

3

#### Creating a two dimensional array - MATRIX

In [9]:
regular_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

The above matrix is LIKE old school matrix - flat and boring

In [10]:
regular_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Accessing it is the same way - in any other language. To grab, 5 we will go to 1,0

In [11]:
regular_matrix[1][0]

5

#### Numpy's matrix is more cute and easy to access

In [12]:
numpy_matrix = np.array(regular_matrix)

In [13]:
numpy_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Notice that above, the representation too is like a real matrix, with row and column. Accessing it the old way

In [14]:
numpy_matrix[1][0]

5

###### Accessing it that is closer to textbook

In [15]:
numpy_matrix[1,0]

5

###### Selecting a column or a specific subs-matrix like rows 1 to 2 and column 1 to 3 is like below.

In [16]:
numpy_matrix[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

###### Accessing only a single column

In [17]:
numpy_matrix[:,1:2]

array([[ 2],
       [ 6],
       [10]])

###### Accessing a single row

In [18]:
numpy_matrix[1:2,:]

array([[5, 6, 7, 8]])

#### Some built in functions in numpy to generate arrays

In [19]:
gen_array = np.arange(0,6)

In [20]:
gen_array

array([0, 1, 2, 3, 4, 5])

###### Reshape changes the shape - from 1D to 2D Array, or RATHER CALL IT A MATRIX

In [21]:
reshaped = gen_array.reshape(2,3)

In [22]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
reshaped_2 = gen_array.reshape(3,2)

In [24]:
reshaped_2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
reshaped_3 = gen_array.reshape(1,2,3)

In [26]:
reshaped_3

array([[[0, 1, 2],
        [3, 4, 5]]])

##### Identity Matrix

In [27]:
identity_matrix = np.eye(10)

In [28]:
identity_matrix

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

##### Zero Matrix

In [29]:
zero_matrix = np.zeros(10)

In [30]:
zero_matrix

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [31]:
zero_matrix.reshape(2,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [32]:
zero_matrix.reshape(5,2)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

##### Adding 5 to all the elements of a regular array, the numpy way

In [33]:
regular_array+5

TypeError: can only concatenate list (not "int") to list

Adding 5 to all the elements of a numpy array

In [34]:
numpy_matrix +5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

###### The above feature is called broadcasting - the operation is broadcasted to all elements of the array

##### Addition of two arrays in numpy

In [35]:
array_one = np.arange(25, 45, 5)

In [36]:
array_one.reshape(2,2)

array([[25, 30],
       [35, 40]])

In [37]:
array_two = np.arange(104, 124, 5)

In [38]:
array_two.reshape(2,2)

array([[104, 109],
       [114, 119]])

In [39]:
array_one + array_two

array([129, 139, 149, 159])

In [40]:
(array_one+array_two).reshape(2,2)

array([[129, 139],
       [149, 159]])

In [41]:
array_one.transpose()

array([25, 30, 35, 40])

###### Some functions to generate arrays and numbers

In [47]:
dist_even = np.linspace(1,20,10)

In [48]:
dist_even

array([  1.        ,   3.11111111,   5.22222222,   7.33333333,
         9.44444444,  11.55555556,  13.66666667,  15.77777778,
        17.88888889,  20.        ])

###### Getting 5 numbers from normal standard distribution

In [49]:
np.random.rand(5)

array([ 0.98285698,  0.08112772,  0.3604089 ,  0.07978693,  0.75527868])

###### Two dimensional random

In [50]:
np.random.randn(4,4)

array([[ 0.91805819,  0.29496802,  1.46521352, -0.28873863],
       [ 0.40609237,  1.49971083,  0.13133038, -0.47737668],
       [-0.44469514,  0.05164036,  0.51226829,  0.70612278],
       [ 0.18457168, -0.3478823 ,  0.85180983, -1.26390686]])

###### Random Integer between low to high - high exclusive

In [52]:
np.random.randint(1,100)

16

###### Random array integer matrix- with a specific size, between a range

In [56]:
np.random.randint(1,100, 10)

array([59, 25, 63, 31,  2, 59, 14, 75, 22, 25])

###### rand(d0, d1, ..., dn)

Random values in a given shape.

In [68]:
np.random.rand(3,2,3)

array([[[ 0.01220802,  0.14039881,  0.13269647],
        [ 0.00420548,  0.7349343 ,  0.22946267]],

       [[ 0.36155688,  0.06537084,  0.05713546],
        [ 0.79236151,  0.84316287,  0.2094454 ]],

       [[ 0.32344935,  0.51885083,  0.92906083],
        [ 0.55953159,  0.47934058,  0.35427204]]])

In [69]:
ranarr = np.random.randint(0,50,10)

In [70]:
ranarr

array([29, 32,  3, 46,  6, 17,  9, 25, 38, 34])

In [73]:
ran_arr = np.random.rand(3,2,3)

In [74]:
ran_arr

array([[[ 0.65695795,  0.9281175 ,  0.78960646],
        [ 0.94932279,  0.31399449,  0.99549161]],

       [[ 0.79083209,  0.10166652,  0.80804403],
        [ 0.07713782,  0.71469331,  0.57615596]],

       [[ 0.05103011,  0.33194209,  0.66167024],
        [ 0.67330743,  0.21642316,  0.12878863]]])

###### Min, Max, Position of min, max of array

In [75]:
ran_arr.min()

0.05103011060648377

In [76]:
ran_arr.max()

0.99549160525044433

In [77]:
ran_arr.argmin()

12

In [78]:
ran_arr.argmax()

5

###### Getting the shape of array

In [79]:
ran_arr.shape

(3, 2, 3)

In [80]:
ranarr.shape

(10,)

###### Type of the array

In [82]:
ran_arr.dtype

dtype('float64')

### Numpy Indexing and Selection

In [83]:
sample_array = np.arange(0,11)

In [84]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
sample_array[2]

2

In [88]:
slice_sample_array = sample_array[0:6]

In [89]:
slice_sample_array

array([0, 1, 2, 3, 4, 5])

###### Slice is just a VIEW of the original ARRAY

In [90]:
slice_sample_array[:] = 99

In [91]:
slice_sample_array

array([99, 99, 99, 99, 99, 99])

In [92]:
sample_array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [94]:
arr_copy = sample_array.copy()

In [95]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [96]:
arr_copy + 5

array([104, 104, 104, 104, 104, 104,  11,  12,  13,  14,  15])

In [97]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [99]:
arr_2d = np.array([[5,10,15],[20,23,30],[35,40,45]])

In [100]:
arr_2d

array([[ 5, 10, 15],
       [20, 23, 30],
       [35, 40, 45]])

In [101]:
arr_2d[0][0]

5

In [102]:
arr_2d[(0,0)]

5

In [103]:
arr_2d[0,0]

5

In [104]:
arr_2d[:1,:1]

array([[5]])

###### Boolean array, from existing array

In [105]:
bool_arr = arr_2d > 5

In [106]:
bool_arr

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

###### Creating an array conditionally from two array

In [108]:
arr_2d[bool_arr]

array([10, 15, 20, 23, 30, 35, 40, 45])

###### Condition selection - Type 2

In [109]:
arr_2d[arr_2d > 5]

array([10, 15, 20, 23, 30, 35, 40, 45])

#### Numpy Operations
    Array with Array
    Array with Scalars
    Universal Array Function

Adding, Substracting, Multiplication

In [111]:
new_array = np.array([0,1,2,3,4,5,6,7,8,9,0])

In [112]:
new_array*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90,  0])

In [113]:
new_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [114]:
new_array + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14,  5])

In [115]:
new_array - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4, -5])

In [116]:
new_array/0

D:\Installs\Anaconda3\envs\tfn\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
D:\Installs\Anaconda3\envs\tfn\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  nan])

In [117]:
new_array/new_array

D:\Installs\Anaconda3\envs\tfn\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,  nan])

In [118]:
new_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81,  0])

In [120]:
np.sqrt(new_array)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,  0.        ])

In [122]:
np.max(new_array)

9

In [124]:
np.sin(new_array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,  0.        ])

In [125]:
np.log(new_array)

D:\Installs\Anaconda3\envs\tfn\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
              -inf])

###### Universal function (ufunc) https://docs.scipy.org/doc/numpy/reference/ufuncs.html