The first thing to do to be able to use numpy is to import it. Commonly use acronym is np

In [2]:
import numpy as np

Regular array examples

In [4]:
regular_array = [1, 2, 3, 4]
regular_array

[1, 2, 3, 4]

In [5]:
type(regular_array)

list

The regular array can be cast into Numpy's array

In [6]:
np_array = np.array(regular_array)

In [7]:
np_array

array([1, 2, 3, 4])

Notice the type of above array is not list, but it is numpy.ndarray

In [8]:
type(np_array)

numpy.ndarray

The numpy arrays can be accesses just like regular arrays + its own way.

In [10]:
np_array[2]

3

#### Creating a two dimensional array - MATRIX

In [11]:
regular_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

The above matrix is LIKE old school matrix - flat and boring

In [12]:
regular_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Accessing it is the same way - in any other language. To grab, 5 we will go to 1,0

In [13]:
regular_matrix[1][0]

5

#### Numpy's matrix is more cute and easy to access

In [14]:
numpy_matrix = np.array(regular_matrix)

In [15]:
numpy_matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Notice that above, the representation too is like a real matrix, with row and column. Accessing it the old way

In [16]:
numpy_matrix[1][0]

5

Accessing it that is closer to textbook

In [17]:
numpy_matrix[1,0]

5

Selecting a column or a specific subs-matrix like rows 1 to 2 and column 1 to 3 is like below.

In [19]:
numpy_matrix[:2,:3]

array([[1, 2, 3],
       [5, 6, 7]])

Accessing only a single column

In [20]:
numpy_matrix[:,1:2]

array([[ 2],
       [ 6],
       [10]])

Accessing a single row

In [22]:
numpy_matrix[1:2,:]

array([[5, 6, 7, 8]])

#### Some built in functions in numpy to generate arrays

In [26]:
gen_array = np.arange(0,6)

In [27]:
gen_array

array([0, 1, 2, 3, 4, 5])

In [28]:
reshaped = gen_array.reshape(2,3)

In [29]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
reshaped_2 = gen_array.reshape(3,2)

In [31]:
reshaped_2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [32]:
reshaped_3 = gen_array.reshape(1,2,3)

In [33]:
reshaped_3

array([[[0, 1, 2],
        [3, 4, 5]]])

##### Identity Matrix

In [34]:
identity_matrix = np.eye(10)

In [35]:
identity_matrix

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

##### Zero Matrix

In [37]:
zero_matrix = np.zeros(10)

In [39]:
zero_matrix

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [40]:
zero_matrix.reshape(2,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [42]:
zero_matrix.reshape(5,2)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

##### Adding 5 to all the elements of a regular array, the numpy way

In [44]:
regular_array+5

TypeError: can only concatenate list (not "int") to list

Adding 5 to all the elements of a numpy array

In [45]:
numpy_matrix +5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

The above feature is called broadcasting - the operation is broadcasted to all elements of the array

##### Addition of two arrays in numpy

In [46]:
array_one = np.arange(25, 45, 5)

In [48]:
array_one.reshape(2,2)

array([[25, 30],
       [35, 40]])

In [53]:
array_two = np.arange(104, 124, 5)

In [54]:
array_two.reshape(2,2)

array([[104, 109],
       [114, 119]])

In [55]:
array_one + array_two

array([129, 139, 149, 159])

In [56]:
(array_one+array_two).reshape(2,2)

array([[129, 139],
       [149, 159]])

In [59]:
array_one.transpose()

array([25, 30, 35, 40])